contact/urls.py
from django.conf.urls import url, include
from django.urls import path
from .views import contactus, all_contacts


app_name = "contact"

urlpatterns = [
    path('',  contactus, name="contactus"),
    path("list/", view=all_contacts, name="contactlist"),

]

person/urls.py
from django.urls import path
from .views import team

urlpatterns = [
    path('', team, name="persons"),
]

project/urls.py
from django.conf.urls import url, include
from django.urls import path

from .views import all_projects, project_detail

urlpatterns = [
    path('',  all_projects, name="projects-view"),
    path(r'^detail/(?P<pk>\d+)/$', project_detail, name="project-detail"),
    ]

teamwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from contact import urls as urls_contact
from person.views import team
from project import urls as urls_project
from person import urls as urls_person

urlpatterns = [
    path('', team, name='persons'),
    path('admin/', admin.site.urls),
    path("contact/", include(urls_contact)),
    path("projects/", include(urls_project)),

]

contact/models.py
from django.db import models


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.TextField(max_length=50)
    message = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email
        return self.company

    class Meta:
        ordering = ['-created']

person/models.py
from django.db import models


# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    description = models.TextField(max_length=300)
    title = models.CharField(max_length=100)
    Linkedin_url = models.CharField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
        return self.email

    class Meta:
        ordering = ['-created']
        ordering = ['-updated']

project/models.py
from django.db import models


# Create your models here.
class Project(models.Model):
    description = models.TextField(max_length=1000)
    overview = models.TextField(max_length=500)
    title = models.CharField(max_length=100)
    tools = models.CharField(max_length=200)
    Link = models.CharField(max_length=200)
    dashbord_image = models.ImageField(upload_to='images/%y/%m/%d/', max_length=255, null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
        return self.link

    class Meta:
        ordering = ['-created']
        ordering = ['-updated']

contact/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

contact/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Contact
from .forms import ContactForm


# Create your views here.

def contactus(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'contact/success.html')
    form = ContactForm()
    context = {'form': form}
    return render(request, 'contact/contact.html', context)


def all_contacts(request):
    contacts = Contact.objects.all()
    paginator = Paginator(contacts, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    return render(request, "contact/allcontacts.html", {"contacts": contacts})

person/views.py
from django.shortcuts import render
from .models import Person


# Create your views here.
def team(request):
    persons = Person.objects.all()
    return render(request, "person/index.html", {"persons": persons})

project/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Project


# Create your views here.

def all_projects(request):
    projects = Project.objects.all()
    paginator = Paginator(projects, 9)
    page = request.GET.get('page')
    projects = paginator.get_page(page)
    return render(request, "project/allprojects.html", {"projects": projects})


def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    return render(request, "project/projectdetail.html", {"project": project})

templates/contact/allcontacts.html
{% load static i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Team Website - Messages List </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="authors" content="Souhail Harrathi & Jad Estephan">
     <!-- ============================ Style & UNICONS CSS --============================ -->
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css'%}" >
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

</head>

<!-- ============================  Header ============================ -->
    <!-- ============================  Header ============================ -->
    <header class="header" id="header">
        <nav class="nav container">
            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list grid">
                    <li class="nav__item">
                        <a href="/" class="nav__link">
                            <i class="uil uil-house-user nav__icon"></i>Home
                        </a>
                        <a href="{% url 'projects-view' %}"  class="nav__link">
                            <i class="uil uil-brain nav__icon"></i>Projects
                        </a>
                        <a href="{% url 'contact:contactus' %}" class="nav__link">
                            <i class="uil uil-envelope nav__icon"></i>Contact
                        </a>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'contact:contactlist' %}" class="nav__link">
                            <i class="uil uil-envelope nav__icon"></i>Messages List
                        </a>
                        {% endif %}
                    </li>

                </ul>
                <i class="uil uil-times nav__close" id="nav-close"></i>
            </div>

            <div class="nav__btns">
                <!-- Theme change button -->
                <i class="uil uil-moon change-theme" id="theme-button"></i>

                <div class="nav__toggle" id="nav-toggle">
                    <i class="uil uil-apps nav__icon"></i>
                </div>
            </div>
        </nav>
    </header>

<body>
    <main>

        <section class="contact section" id="contact">
            <h2 class="section__title">Messages List </h2>
            <span class="section__subtitle">Sorted by the received time</span>
            <div class="contact__container container grid">
                {% for contact in contacts %}

                <ul>
                    <div class="message container ">
                        <li><h1>Message id :  {{ contact.pk }}</h1></li>
                        <li><a>Name : {{ contact.name }}</a></li>
                        <li><a>Email : {{ contact.email }}</a></li>
                        <li><a>Subject : {{ contact.subject }}</a></li>
                        <li><a>Message : </a></li>
                        <ul><a>{{ contact.message }}</a></ul>
                        <li><a>Date : {{ contact.created }}</a></li>
                    </div>
                </ul>
                <br>

			{% endfor %}


            </div>

        </section>
    </main>

        <!-- ============================  FOOTER ============================ -->
    <footer class="footer">
        <div class="footer__bg">
            <div class="footer__container container grid">
                <ul class="footer__links">
                    <li>
                        <a href="/" class="footer__link">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'projects-view' %}" class="footer__link">Projects</a>
                    </li>
                    <li>
                        <a href="{% url 'contact:contactus' %}" class="footer__link">
                            <i class="uil uil-envelope nav__icon"></i>Contact Us
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'contact:contactlist' %}" class="footer__link">
                            <i class="uil uil-envelope nav__icon"></i>Messages List


                        </a>
                    </li>
                    {% endif %}
                </ul>

            </div>
        </div>

    </footer>

    <script src="{% static './js/main.js'%}"></script>
</body>
</html>

templates/contact/contact.html
{% load static i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Team Website - Contact Us </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="authors" content="Souhail Harrathi & Jad Estephan">
     <!-- ============================ Style & UNICONS CSS --============================ -->
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css'%}" >
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

</head>

<!-- ============================  Header ============================ -->
    <header class="header" id="header">
        <nav class="nav container">
            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list grid">
                    <li class="nav__item">
                        <a href="/" class="nav__link">
                            <i class="uil uil-house-user nav__icon"></i>Home
                        </a>
                        <a href="{% url 'projects-view' %}"  class="nav__link">
                            <i class="uil uil-brain nav__icon"></i>Projects
                        </a>
                        <a href="{% url 'contact:contactus' %}" class="nav__link">
                            <i class="uil uil-envelope nav__icon"></i>Contact
                        </a>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'contact:contactlist' %}" class="nav__link">
                            <i class="uil uil-envelope nav__icon"></i>Messages List
                        </a>
                        {% endif %}
                    </li>

                </ul>
                <i class="uil uil-times nav__close" id="nav-close"></i>
            </div>

            <div class="nav__btns">
                <!-- Theme change button -->
                <i class="uil uil-moon change-theme" id="theme-button"></i>

                <div class="nav__toggle" id="nav-toggle">
                    <i class="uil uil-apps nav__icon"></i>
                </div>
            </div>
        </nav>
    </header>

<body>
    <main>

        <section class="contact section" id="contact">
            <h2 class="section__title">Contact </h2>
            <span class="section__subtitle">Get in touch</span>
            {% block content %}
            <div class="contact__container container grid">
                <form method="post" name="contactForm" id="contact_form" action="" class="contact__form grid" >
                    <div class="contact__inputs grid">
                            {% csrf_token %}
                                {{ form }}
                        <div>
                            <button  class="button button--flex" type="submit" form="contact_form" value="Submit">
                                Send Message <i class="uil uil-message button-icon"></i>
                            </button>

                        </div>
                    </div>

                </form>
                {% endblock %}

            </div>

        </section>
    </main>

       <!-- ============================  FOOTER ============================ -->
    <footer class="footer">
        <div class="footer__bg">
            <div class="footer__container container grid">
                <ul class="footer__links">
                    <li>
                        <a href="/" class="footer__link">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'projects-view' %}" class="footer__link">Projects</a>
                    </li>
                    <li>
                        <a href="{% url 'contact:contactus' %}" class="footer__link">
                            <i class="uil uil-envelope nav__icon"></i>Contact Us
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'contact:contactlist' %}" class="footer__link">
                            <i class="uil uil-envelope nav__icon"></i>Messages List


                        </a>
                    </li>
                    {% endif %}
                </ul>

            </div>
        </div>

    </footer>

    <script src="{% static './js/main.js'%}"></script>
</body>
</html>

templates/contact/success.html
{% load static i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Team Website - Message has been sent </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="authors" content="Souhail Harrathi & Jad Estephan">
     <!-- ============================ Style & UNICONS CSS --============================ -->
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css'%}" >
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

</head>

<!-- ============================  Header ============================ -->
    <header class="header" id="header">
        <nav class="nav container">
            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list grid">
                    <li class="nav__item">
                        <a href="/" class="nav__link">
                            <i class="uil uil-house-user nav__icon"></i>Home
                        </a>
                        <a href="{% url 'projects-view' %}"  class="nav__link">
                            <i class="uil uil-brain nav__icon"></i>Projects
                        </a>
                        <a href="{% url 'contact:contactus' %}" class="nav__link">
                            <i class="uil uil-envelope nav__icon"></i>Contact
                        </a>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'contact:contactlist' %}" class="nav__link">
                            <i class="uil uil-envelope nav__icon"></i>Messages List
                        </a>
                        {% endif %}
                    </li>

                </ul>
                <i class="uil uil-times nav__close" id="nav-close"></i>
            </div>

            <div class="nav__btns">
                <!-- Theme change button -->
                <i class="uil uil-moon change-theme" id="theme-button"></i>

                <div class="nav__toggle" id="nav-toggle">
                    <i class="uil uil-apps nav__icon"></i>
                </div>
            </div>
        </nav>
    </header>

<body>
    <main>

        <section class="contact section" id="contact">
            <h2 class="section__title">Message has been sent  </h2>
            <span class="section__subtitle">You will receive a reply as soon as possible</span>
            {% block content %}
            <div class="contact__container container grid">
                <a  class="button button--flex"  href="/">
                                Return to Home Page <i class="uil uil-home button-icon"></i>
                </a>
                {% endblock %}

            </div>

        </section>
    </main>

        <!-- ============================  FOOTER ============================ -->
    <footer class="footer">
        <div class="footer__bg">
            <div class="footer__container container grid">
                <ul class="footer__links">
                    <li>
                        <a href="/" class="footer__link">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'projects-view' %}" class="footer__link">Projects</a>
                    </li>
                    <li>
                        <a href="{% url 'contact:contactus' %}" class="footer__link">
                            <i class="uil uil-envelope nav__icon"></i>Contact Us
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'contact:contactlist' %}" class="footer__link">
                            <i class="uil uil-envelope nav__icon"></i>Messages List


                        </a>
                    </li>
                    {% endif %}
                </ul>

            </div>
        </div>

    </footer>

    <script src="{% static './js/main.js'%}"></script>
</body>
</html>

templates/person/index.html
{% load static i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Team Website - Home </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="authors" content="Souhail Harrathi & Jad Estephan">
     <!-- ============================ Style & UNICONS CSS --============================ -->
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css'%}" >
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

</head>

<!-- ============================  Header ============================ -->
    <!-- ============================  Header ============================ -->
    <header class="header" id="header">
        <nav class="nav container">
            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list grid">
                    <li class="nav__item">
                        <a href="/" class="nav__link">
                            <i class="uil uil-house-user nav__icon"></i>Home
                        </a>
                        <a href="{% url 'projects-view' %}"  class="nav__link">
                            <i class="uil uil-brain nav__icon"></i>Projects
                        </a>
                        <a href="{% url 'contact:contactus' %}" class="nav__link">
                            <i class="uil uil-envelope nav__icon"></i>Contact
                        </a>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'contact:contactlist' %}" class="nav__link">
                            <i class="uil uil-envelope nav__icon"></i>Messages List
                        </a>
                        {% endif %}
                    </li>

                </ul>
                <i class="uil uil-times nav__close" id="nav-close"></i>
            </div>

            <div class="nav__btns">
                <!-- Theme change button -->
                <i class="uil uil-moon change-theme" id="theme-button"></i>

                <div class="nav__toggle" id="nav-toggle">
                    <i class="uil uil-apps nav__icon"></i>
                </div>
            </div>
        </nav>
    </header>
    <!-- ============================  Main ============================ -->
    <main class="main">
        <!-- ============================  HOME  ============================ -->
        <section class="home section" id="home">
            <div class="home__container container grid">
                <div class="home__data">
                    <h1 class="home__title">Welcome in our team portfolio</h1> <br>
                    <p class="home__description">Welcome to our team's website, where we showcase our passion for innovation and dedication to creating exciting projects. Our team consists of two students who are passionate about using technology to make a positive impact on the world.
                        On this website, you will find information about the projects we have worked on, as well as our ongoing work. We are excited to share our progress and accomplishments with you, and hope that our projects inspire you to pursue your own innovative ideas.
                        Through our website, we aim to provide a glimpse into our creative process, and highlight the various technologies and tools we use to bring our ideas to life. We believe that collaboration is key to success, and we invite you to join us on our journey towards creating impactful projects that make a difference. <br /> - Thank you for visiting our website, and we hope that you find it informative and inspiring. If you have any questions or feedback, please don't hesitate to reach out to us. </p>
                    <a href="{% url 'contact:contactus' %}" class="button button--flex">
                        Contact  <i class="uil uil-message button-icon"></i>
                    </a>

                </div>
            </div>
        </section>

        <!-- ============================  Team  ============================ -->

    <section class="about section" id="about">
        <h2 class="section__title">Meet The Team</h2>
        <br>
        {% for person in persons %}
        <div class="u-container-layout ">
            <div class="about__container container ">


                <div class="about_data">
                     <!-- To Use in the future -->
                    <div class="about__info">
                            <div>
                                <span class="section__subtitle">
                                    <ul>
                                        <li><b>{{ person.name }}</b></li>
                                        <li>{{ person.title }}</li>

                                    </ul>  </span>
                    </div>

                    <p class="about__description">
                                {{ person.description }}
                    </p>

                        <div class="home__social">
                            <a href={{ person.Linkedin_url }} target="_blank" class="home__social-icon">
                                <i class="uil uil-linkedin-alt"></i>
                            </a>
                        </div>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}

    </section>


<!-- ============================  FOOTER ============================ -->
    <footer class="footer">
        <div class="footer__bg">
            <div class="footer__container container grid">
                <ul class="footer__links">
                    <li>
                        <a href="/" class="footer__link">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'projects-view' %}" class="footer__link">Projects</a>
                    </li>
                    <li>
                        <a href="{% url 'contact:contactus' %}" class="footer__link">
                            <i class="uil uil-envelope nav__icon"></i>Contact Us
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'contact:contactlist' %}" class="footer__link">
                            <i class="uil uil-envelope nav__icon"></i>Messages List


                        </a>
                    </li>
                    {% endif %}
                </ul>

            </div>
        </div>

    </footer>

    <script src="{% static './js/main.js'%}"></script>
</body>
</html>

templates/project/allprojects.html
{% load static i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Team Website - Our Projects </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="authors" content="Souhail Harrathi & Jad Estephan">
     <!-- ============================ Style & UNICONS CSS --============================ -->
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css'%}" >
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

</head>

    <!-- ============================  Header ============================ -->
    <header class="header" id="header">
        <nav class="nav container">
            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list grid">
                    <li class="nav__item">
                        <a href="/" class="nav__link">
                            <i class="uil uil-house-user nav__icon"></i>Home
                        </a>
                        <a href="{% url 'projects-view' %}"  class="nav__link">
                            <i class="uil uil-diary nav__icon "></i>Projects
                        </a>
                        <a href="{% url 'contact:contactus' %}" class="nav__link">
                            <i class="uil uil-envelope nav__icon"></i>Contact
                        </a>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'contact:contactlist' %}" class="nav__link">
                            <i class="uil uil-envelope nav__icon"></i>Messages List
                        </a>
                        {% endif %}
                    </li>

                </ul>
                <i class="uil uil-times nav__close" id="nav-close"></i>
            </div>

            <div class="nav__btns">
                <!-- Theme change button -->
                <i class="uil uil-moon change-theme" id="theme-button"></i>

                <div class="nav__toggle" id="nav-toggle">
                    <i class="uil uil-apps nav__icon"></i>
                </div>
            </div>
        </nav>
    </header>

<body>
    <main>

        <section class="about section" id="about">
            {% for project in projects %}
            <h2 class="section__title">
                {{ project.title }}
            </h2>
            <div class="about__container container grid">
                <img src="{% static '/img/soon.jpg' %}" alt="" class="about__img" />

                <div class="about_data">
            <span class="section__subtitle">Overview</span>
                    <p class="about__description">
                        {{ project.overview }}
                    </p>
                    <!-- To Use in the future -->
                    <div class="about__info">
                        <div>
                            <span class="about__info-tools">Tools : {{ project.tools }}</span>
                            <span class="about__info-name">  </span>
                        </div>

                    </div>
                    <div class="about__buttons">
                        <a href="{% url 'project-detail' pk=project.pk  %}" class="button button--flex">
                            Project Details <i class="uil uil-download-alt button_icon"></i>
                        </a>

                    </div>

                </div>

            </div>

        {% endfor %}
        </section>
    </main>

       <!-- ============================  FOOTER ============================ -->
    <footer class="footer">
        <div class="footer__bg">
            <div class="footer__container container grid">
                <ul class="footer__links">
                    <li>
                        <a href="/" class="footer__link">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'projects-view' %}" class="footer__link">Projects</a>
                    </li>
                    <li>
                        <a href="{% url 'contact:contactus' %}" class="footer__link">
                            <i class="uil uil-envelope nav__icon"></i>Contact Us
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'contact:contactlist' %}" class="footer__link">
                            <i class="uil uil-envelope nav__icon"></i>Messages List


                        </a>
                    </li>
                    {% endif %}
                </ul>

            </div>
        </div>

    </footer>

    <script src="{% static './js/main.js'%}"></script>
</body>
</html>